### PR TITLE
Map changes and removing Krokodil

### PR DESCRIPTION
**Pull request by KillerGryphon**
## About The Pull Request

So, a few things. Casino is broken rn, I've removed the ladder, someone can fix the buttons and it can work properly later, it's all still there, the ladder is just gone. I've also swapped the BoS bunker and that raider bunker locations, back to where they originally were, because it turns out having the BoS be RIGHT next to the NCR mine isn't the greatest idea in the world. 

Lastly, I've removed all (but a changelog) traces of Krokodil from the code, zip, gone, no more zombies like that.

### CODE REVIEW

**Comment by EgorDinamit** [comment]
Why the Krokodil? This is just a random change you add into a map edit.

**Comment by DeveloperLoser** [comment]
Also, krokidil dosn't make zombies?

**Comment by thedarkcrusader** [comment]
> Why the Krokodil? This is just a random change you add into a map edit.

Seams like a random change why Krokodil?

**Comment by EgorDinamit** [comment]
> Also, krokodil dosn't make zombies?

It changes their skin to resemble a zombie. That's all it does.

**Comment by KillerGryphon** [comment]
Done at the behest of the rest of staff, we removed it for a reason before, now we gotta do it again... also it appears that staying up until 5am coding made me forget to check my code. Updating shortly.

**Comment by BigBigga** [comment]
I'dunno, I personally really like the stuff inside of the vault, plus, you have to go through what is basically mutant Vietnam to get it. Additionally, I've seen people get into the casino's main prize room MULTIPLE times, even though it's ''broken''. Leave it as it is, just fix the buttons or it'll be a REAL real long while before someone bothers, if the ladder is actually removed.

**Comment by AdamElTablawy** [comment]
conflicts

**Comment by Singularity69** [comment]
> unno, I personally really like the stuff inside of the vault, plus, you have to go through what is basically mutant Vietnam to get it. Additionally, I've seen people get into the casino's main prize room MULTIPLE times, even though it's ''broken''. Leave it as it is, just fix the buttons or it'll be a REAL real long while before someone bothers, if the ladder is act

this

**Comment by KillerGryphon** [comment]
For everyone worried about the casino being removed, this is temporary until mappers figure out how to make it work without admins having to open it every time. It takes up time when other things could be done!

**Comment by KillerGryphon** [comment]
> I'dunno, I personally really like the stuff inside of the vault, plus, you have to go through what is basically mutant Vietnam to get it. Additionally, I've seen people get into the casino's main prize room MULTIPLE times, even though it's ''broken''. Leave it as it is, just fix the buttons or it'll be a REAL real long while before someone bothers, if the ladder is actually removed.

also, every time they've gotten in, it's C4, or admins letting them in. I can look into it later, but it needs a patch for now.

**Comment by KillerGryphon** [comment]
It seems work is needed, closing this to reopen with just map changes.

**Pull request closed without merging**
