### PR TITLE
Revert "Revert "Oasis Police Department""

### PR DESCRIPTION
**Pull request by AdamElTablawy**
Reverts nokele/Fortune13#383

selfmerged PR with no reasoning

### CODE REVIEW

**Comment by ogrigbe** [comment]
Is this ready?

**Comment by AdamElTablawy** [comment]
i mean you can just explain your reasoning as to why it was removed rigbe since you're the one who merged it

but go ahead merge at will it won't break anythng

**Comment by John-Dang** [comment]
> i mean you can just explain your reasoning as to why it was removed rigbe since you're the one who merged it
> 
> but go ahead merge at will it won't break anythng

I had tested my PR and items weren't showing up with the proper graphics, and something was wrong with the menu when I started a local server with the latest version. I told Rigbe to unmerge it until the PR was properly made. It needs fine tuning.

**Comment by AdamElTablawy** [comment]
ok

**Pull request closed without merging**
