### PR TITLE
Adds back vault!

### PR DESCRIPTION
**Pull request by DeveloperLoser**
## About The Pull Request

Simply sets the vault slots back to what they were minus some slots. Major map changes to.

## Why It's Good For The Game

The vault is generally disliked for how the people within power game, and in the case of the PR that removed it, clearly titled as "tweaking stuff", to many job slots was cited as a problem.

First power gaming, vault generally keeps to itself and if they do ruffle feathers, are easy to kill/cut off from the surface. and while they have access to some pretty mean tech, so do the BOS and Enclave, who also get better armor, and the components to easily craft weapons en-mass. Additionally they now have a 

Secondly slots. The vault does have a stupid fucking amount of slots coming in at 19, that has been changed, mainly reducing the number of engineers and dwellers. Additionally, the servers population has rapidly increased, and we are now regularly near the top of the server list. If the need to decrease the number of people in vault more is felt, then that can be easily done, but it shouldn't just be completely removed, especially in an un-tagged, badly named PR.

Third, vault is a great place to learn and play around. Its a safe, secure bunker in the corner of the darkest part of the map where you can have fun conversations, play around with whatever bullshit you want, and generally learn and have fun.

Finally, interaction. The vault is now more trade oriented, having a dedicated trade area and easier access with a ladder leading down to them just north of oasis in a new abandoned subway building

Also, if this PR gets merged then I'll be more than happy to expand on the vaults content, like
- giving them station like objectives. (something to do for the round, tg vault moment)
- starting the vault in a state of decay, requiring the dwellers to repair it. (more on the teaching new players side)

Since there were quite a few slots, here's how I've changed/removed some. (Because details fucking matter!)

- Overseer:                
       - 1 Before
       - 1 After
       -  Vault needs a leader (If someone ever decides to be one)
- Chief of Security:   
       - 1 Before
       -  0 After
       - The overseer works fine as a HOS.
- Doctor:                  
       - 2 Before
       - 2 After
       - One for actually treating people, the other is just a chemist.
- Scientist:                
       - 2 Before
       - 2 After
       - Science! That's what the vaults all about.
- Security Officer:     
       - 3 Before
       - 1 After
       - The vault has no solid laws, and if someone's being a shitter, anyone can deal with it.
- Engineer:               
       - 2 Before
       - 1 After
       - The engineering "department" has full access on its doors, and no real job.
- Dweller:            
       - **_8 Before_**
       - 2 After
       - They serve, no purpose. Just an overflow/miner slot.

And with that, vault goes from 19 jobs, to 10. While that's still a fair few, most SSD, Die, Or more likely, don't even join vault.

## Changelog
:cl:
add: Added vault slots back.
fix: Cargo shuttle leaking atmos.
tweak: Forbid/Enforce text.
tweak: The vault itself.
tweak: Cargo crates.
remove: Some vault slots.
remove: TTV's from cargo shuttle.

/:cl:

### CODE REVIEW

**Comment by DeveloperLoser** [comment]
Vault-
Vault1


Subway Station-
subway1

**Comment by dawsonkeyes** [comment]
Failing checks and issues aside, this doesn't help to give the vault the purpose they lacked before. Also, fully honest, that subway station looks like hot garage with absolutely zero decoration whatsoever.

**Comment by Mannybrado** [comment]
subway station is meh, the walls around the vault should be decreased significantly. all of those walls are reinforced, there is no reason it should be like that. and, yes, this doesn't fix the issue of vault having no purpose.

**Comment by Mrfilms** [comment]
I don't care for the subway - its far too empty, plus the buildings it's replacing are relatively iconic as far as the old town goes. I would say you'd be better off adding a smaller building in some other part of the map - perhaps not themed as a subway (I doubt a town like Yuma would have a metro line). Other than that, like Manny said - just thin the walls a bit, its fine otherwise.

**Comment by DeveloperLoser** [comment]
>I don't care for the subway 

>subway station is meh

Yea, I'm not a very good mapper, I'll pop back the old building's and move it to some shack, but Kelo wanted the vault to be much more accessible .

>walls are too thick

>the walls around the vault should be decreased significantly.

Fair point, I'll make them a bit thinner, however if it proves to be a problem, I.e. the Brotherhood/Enclave rush jackhammers into it, then I'll layer it up again/more, or just put un simulated walls around it like the BoS bunker, NCR, and Oasis.

In term's of purpose, the vault is now more trade and tutorial oriented, I was planning on placing helpful book's around but a book DB isn't setup :( Additionally if this does get merged I'll be adding more vault specific things like hostile mob infestations, more damage to repair round start, and specific goals (vault station moment).

**Comment by DeveloperLoser** [comment]
New images:
lemonvault
lemonvaultentrance

**Comment by BigBigga** [comment]
Bruh. Can't wait to have all of the major faction's bases blown up by vault BSA again.

**Comment by Sinbest** [comment]
This is never gonna get merged man, just close it.

**Comment by EgorDinamit** [comment]
The only reason to add Vault back:
image
image

**Comment by DeveloperLoser** [comment]
Well, I fucked something up _really_ badly, so time for another new PR that hopefully fixes this

**Pull request closed without merging**
