### PR TITLE
Reverts vault removal

### PR DESCRIPTION
**Pull request by DeveloperLoser**
## About The Pull Request

Simply sets the vault slots back to what they were minus some slots.
Changes the vault as a whole

Also re-making this PR because I'm sick of getting merge fucked.

## Why It's Good For The Game

The vault is generally disliked for how the people within power game, and in the case of the PR that removed it, clearly titled as "Tweaking Stuff" to many job slots was sited as a problem, however there's a pretty wide band of "issue's" seen with the vault, so I've laid them out here, as well as the solution's I came up with for each.

Problem: Power-gaming
vault generally keeps to itself and if they do ruffle feathers, are easy to kill/cut off from the surface. and while they have access to some pretty mean tech, so do the BOS and Enclave, who also get better armor, and the components to easily craft weapons en-mass. Even then, if the vault runs up to the surface, murders the fucking shit out of people with their max-caps (also easy to remove TTV valves), they should be yelled at by admins for over-escalation, or told off for power gaming.

Problem: Job bloat
The vault does have a stupid fucking amount of slots coming in at 19, that has been changed, mainly reducing the number of engineers and dwellers. Additionally, the servers population has rapidly increased, and we are now regularly near the top of the server list. If the need to decrease the number of people in vault more is felt, then that can be easily done, but it shouldn't just be completely removed, especially in an un-tagged, badly named PR.

Problem: Round interaction
The round's are long lasting, and require interaction from everyone to be widely enjoyable. As such, I've modified the main entrance to the vault into a trading area. The vault has 4 weapon blueprints, as well as RND, so they should have plenty to trade.

Finally vault is a great place to learn and play around. Its a safe, secure bunker in the corner of the darkest part of the map where you can have fun conversations, play around with whatever bullshit you want, and generally learn and have fun.

Also, if this PR gets merged then I'll be more than happy to expand on the vaults content, like
- Giving them station like objectives. (something to do for the round, tg vault moment)
- Mob spawn events/radiation leaks, so the vault has issue's to deal with as the round goes on.
- More round start damage to the vault, other than a blown engine.

Since there were quite a few slots, here's how I've changed/removed some. (Because details fucking matter!)

- Overseer:                
       - 1 Before
       - 1 After
       -  Vault needs a leader (If someone ever decides to be one)
- Chief of Security:   
       - 1 Before
       -  0 After
       - The overseer works fine as a HOS.
- Doctor:                  
       - 2 Before
       - 2 After
       - One for actually treating people, the other is just a chemist.
- Scientist:                
       - 2 Before
       - 2 After
       - Science! That's what the vaults all about.
- Security Officer:     
       - 3 Before
       - 1 After
       - The vault has no solid laws, and if someone's being a shitter, anyone can deal with it.
- Engineer:               
       - 2 Before
       - 0 After
       - The engineering "department" has full access on its doors, and no real job.
- Dweller:            
       - **_8 Before_**
       - 2 After
       - They serve, no purpose. Just an overflow/miner slot.

And with that, vault goes from 19 jobs, to 9. While that's still a fair few, most SSD, Die, Or more likely, don't even join vault.

## Changelog
:cl:
tweak: Tweaked the vault, changing it's entire layout, starting with a badly damaged engine to repair
add: Vault trading area.
remove: Some vault slots, but less than originally. (see this PR)
/:cl:

### CODE REVIEW

**Comment by DeveloperLoser** [comment]
>Only 1 PR open.
>Its my PR.
>Merge conflicts.
Please fucking kill me.

**Comment by Mannybrado** [comment]
this doesn't fix the fundamental issue of vault being a dead-end faction with nothing to do. they serve no purpose other than to take people out of the wastes as a whole. while taking the roles down is a good change, the powergaming and round interaction issues are still going to exist IN THEIR ENTIRETY. giving more people access to RnD is genuinely always a bad thing. always. RnD is not a good system, and having another place where people can get incredibly powerful weapons from in the guise of trading to encourage round interaction(that being, of course, TDM. when all that is useful for them to make is weapons, what do you think will happen?) is a joke. the vault has never worked in the history of fallout13 that wasn't either a place for powergamers to powergame, a place for powergamers to HAND OUT OP weapons/equipment, or for people to do jackshit and ERP, this WILL NOT change that.

**Comment by DeveloperLoser** [comment]
> this doesn't fix the fundamental issue of vault being a dead-end faction with nothing to do. 

There is now repairs, crafting, trading, and more to do.

>they serve no purpose other than to take people out of the wastes as a whole.

This is negated by the trading/10 slot reduction.

> while taking the roles down is a good change, the powergaming and round interaction issues are still going to exist IN THEIR ENTIRETY. 

Virus and TTV crates were the main source of power-gaming. They are or are being removed. The BoS and Enclave both have much more access to power-gaming.

>giving more people access to RnD is genuinely always a bad thing. always. RnD is not a good system, 

I believe there are plans to rework RnD. Also FoA were just given RnD, which I would argue is MUCH more accessible than this. Assuming this gets merged, it can be removed, and then FoA trade with vault for their tools and such, also increasing round interaction.

>and having another place where people can get incredibly powerful weapons from in the guise of trading to encourage round interaction(that being, of course, TDM. when all that is useful for them to make is weapons, what do you think will happen?) is a joke. 

The vault needs resources and outside help to make even a decent quantity of weapons, additionaly these are the same blueprint weapons BoS get, and arent anywhere near as powerful as what BoS, Enclave, and Oasis get. RND also makes far more than just weapons.

>or for people to do jackshit and ERP, this WILL NOT change that.

Read first point. Let people ERP, they're gonna do it regardless.

**Comment by DeveloperLoser** [comment]
Shuttle is currently fucked, wee

**Comment by Mannybrado** [comment]
> There is now repairs, crafting, trading, and more to do.

They could repair and craft before and it didn't change anything. I already explain what "trading" means, but I'll explain it again. "Trading" broken weapons and equipment does nothing but further the issue of powergaming and TDM, because giving people MORE access to broken things will just make people MORE inclined to abuse it.

> Virus and TTV crates were the main source of power-gaming. They are or are being removed. The BoS and Enclave both have much more access to power-gaming.

Sure, alright. The issue? Both are things DR added. Before, neither of those cratets were not accessible to vault, yet vault was still the number 1 powergaming faction due to how they have no responsibility, the immense power RnD gives them, and how they are in the safest place they can possibly be.

> I believe there are plans to rework RnD. Also FoA were just given RnD, which I would argue is MUCH more accessible than this. Assuming this gets merged, it can be removed, and then FoA trade with vault for their tools and such, also increasing round interaction.

I haven't heard anything about and RnD rework. The FoA getting RnD is a bad change, they utterly DO NOT need it.

> The vault needs resources and outside help to make even a decent quantity of weapons, additionaly these are the same blueprint weapons BoS get, and arent anywhere near as powerful as what BoS, Enclave, and Oasis get. RND also makes far more than just weapons.

You mean they need one person to put on a disguise(or not, really), mine out the entire bottom mining layer and fuck off the rest of the round? You know, like both the brotherhood and enclave do already?????????? Adding MORE powerful equipment and saying "Oh, other factions already get overpowered gear so its okay" IS NOT AN ARGUMENT. I cannot BEGIN to wrap my mind around how you think it is.

**Comment by DeveloperLoser** [comment]
>They could repair and craft before and it didn't change anything. I already explained what "trading" means, but I'll explain it again. "Trading" broken weapons and equipment does nothing but further the issue of powergaming and TDM, because giving people MORE access to broken things will just make people MORE inclined to abuse it

What broken things?
Bombs are being nerfed/have been.
Cryo syringes should just be removed but scope.

>they have no responsibility, 

They must remain in vault, trade, and repair vault.

>the immense power RnD gives them,

What power.

>and how they are in the safest place they can possibly be.

They have no armor, overseer PA is == Swat armor from cargo, any faction could wipe them with ease.

>I haven't heard anything about and RnD rework.

Watch discord more, it's come up a few times.

>The FoA getting RnD is a bad change, they utterly DO NOT need it.

Chill out, also why bitch at me for this?

>You mean they need one person to put on a disguise(or not, really),

Quote, "The Vault forbids: ... , Deserting the Vault unless it is rendered unhospitable."
Can also be changed to be more specific

>mine out the entire bottom mining layer and fuck off the rest of the round? You know, like both the brotherhood and enclave do already??????????

Again, chill. Enclave/Bos have much more ore available. Look at the actual map before complaining about it.

>Adding MORE powerful equipment and saying

What gear.

> "Oh, other factions already get overpowered gear so it's okay" IS NOT AN ARGUMENT.

Where do I say this? Also chill.
 
> I cannot BEGIN to wrap my mind around how you think it is.

"Lol" said the nerd. "lmao"

**Comment by Mannybrado** [comment]
OK. You are either too stupid to understand my points are are just ignoring them. I'm not going to repeat myself, so whatever.

**Comment by DeveloperLoser** [comment]
So, this is fucked. I have no idea why, but I've backed up the map files so hopefully just making a new branch off of main will work...

**Pull request closed without merging**
