### PR TITLE
Remove Sneedclave Two

### PR DESCRIPTION
**Pull request by Tokorizo**
## About The Pull Request

Title says all

## Why It's Good For The Game

After talking, staff agreed for its removal, Enclave will be disabled for a set amount of time and in its place will be put a new bunker. That's pretty much it.

## Changelog
:cl:
add: bunker
del: sneedclave
/:cl:

### CODE REVIEW

**Comment by EgorDinamit** [comment]
enclab

Mmm yes, democracy.

**Comment by UntoldTactics** [comment]
About time

**Comment by EgorDinamit** [comment]
Mmmm yes, democracy.
image

**Comment by Singularity69** [comment]
despot administration staff smh
literally 1984

**Comment by Misha600** [comment]
> 
> 
> Mmmm yes, democracy.
> image

I didn't know Fortune was run by tgstation.

**Comment by bardinatavern4** [comment]
Why are you trying to remove something that the majority of the community wants to stay? if they're that bad, then rework them, edit the jobs, change their role in the round. It's this kind of 0 effort "Delete things that I don't like" attitude we really need to get rid of. Vigilante also just got removed because someone didn't like it personally, and didn't feel like reworking it at all. It's really shitty for the game.

**Comment by Schwaglord** [comment]
Cringe.

**Comment by Burtuu** [comment]
1984

**Comment by Tokorizo** [comment]
rigbe did a bit of trolling

**Pull request closed without merging**
