### PR TITLE
Empty compost bins at the start, compost more and better foods for more compost

### PR DESCRIPTION
**Pull request by Lobachevskiy**
## About The Pull Request
Start compost bins empty (currently start with 1000 compost). As compensation, most foods are now compostable and the amount of compost also scales with potency, 50 potency being current values (4 for seeds, 10 for produce and foods), 100 potency being double that.

## Why It's Good For The Game
Right now compost bins are really bottomless barrels of fertilizer instead. Even if you empty one, for only 25 planks you can build another one with another 1000 compost. I've never seen anyone actually try to compost anything. This PR attempts to change without making nutrients too scarce. It also adds a little bit of progression to the beginning of tribal gardening.

I intentionally kept the values for average potency the same as they are now, but suggestions for better ones are welcome.

## Changelog
:cl:
del: Compost bins now start empty.
add: However, you can now compost most foods with the exception of meat and dairy.
balance: The amount of compost scales with potency, remaining the same as before at 50.
/:cl:

### CODE REVIEW

**Comment by ogrigbe** [comment]
Hesitant to add this one because it's mainly going to fuck the tribals and legion. Everyone else has relatively easy access to fertilizer. Maybe if you make the starting bin have fertilizer to grow the plants and then encourage them to refill it I'd be on board. Maybe starting at like 200 instead of 1000 ?

**Comment by Lobachevskiy** [comment]
> 
> 
> Hesitant to add this one because it's mainly going to fuck the tribals and legion. Everyone else has relatively easy access to fertilizer. Maybe if you make the starting bin have fertilizer to grow the plants and then encourage them to refill it I'd be on board. Maybe starting at like 200 instead of 1000 ?

It would just need a little bit of jumpstart for the first plants, which can be done with wild plants, starting seeds or potentially stuff from the garbage piles. From then on the resulting produce should be able to sustain it. I also thought about adding something like manure from brahmin later on. Until then I suppose it could start with some fertilizer in it. What about 100? It's enough to grow 10 batches of produce, and also can be supplemented with wild plants.

**Comment by ogrigbe** [comment]
They need to start with something to become self sufficient over time. If you work hard you should be able to maintain so 100 could work. Just something to get a few seeds in the ground because if you think about it not everyone farms food style plants with high yields of fertilizer in them. They farm broc, xander, etc first to get medical supplies out of the way and I don't think those plants offer much fertilizer. I can test that to find out. But yes I can do with 100.

**Comment by Lobachevskiy** [comment]
@ogrigbe

**Pull request merged**
