### PR TITLE
Adds a new faction called The Children of the Cathedral

### PR DESCRIPTION
**Pull request by SpaceSlug2**
## About The Pull Request
Reenables the iron Coven and turns them into the Unity worshipping Children of the Cathedral

## Why It's Good For The Game
Quite a few people have been asking for a Mutant faction and when I was looking through the code I notice the Iron Coven. They are supposed to be a group of healers that have to find each other. Run advertisements about the greatness of the Unity and the High-Priests. While destabilizing the NCR and BOS

## Changelog
:cl:
code: Changed the "Iron Coven" into the Children of the Cathedral changed their Outfits guns and laws
/:cl:

### CODE REVIEW

**Comment by Mannybrado** [comment]
we really don't need more factions man. if someone really wants to play as a mutant they can just pick ghoul or find some FEV. at this point not even half of the server's roles are filled when we're at fucking 80 pop.

**Comment by SpaceSlug2** [comment]
> we really don't need more factions man. if someone really wants to play as a mutant they can just pick ghoul or find some FEV. at this point not even half of the server's roles are filled when we're at fucking 80 pop.

Who fucking cares if slots are filled? The point of factions are for peoples playstyles. If someone wants to play as a doctor type preacher role that attempts to recruit from the ranks of factions then let them play that.

**Comment by Mannybrado** [comment]
sure. they can do that without having an entire faction dedicated for them. this is bloat.

**Comment by SpaceSlug2** [comment]
> sure. they can do that without having an entire faction dedicated for them. this is bloat.

You can say that for ANY other faction

**Comment by Mannybrado** [comment]
I guess I'm going to add in the GLA and DMD as proper factions because some people want to play as mercenaries that work for anyone.

**Comment by SpaceSlug2** [comment]
> I guess I'm going to add in the GLA and DMD as proper factions because some people want to play as mercenaries that work for anyone.

Yeah that's actually a good idea. A faction entirely based around Ghouls.

**Comment by ProfessorPopoff** [comment]
> Who cares if slots are filled? The point of factions are for peoples playstyles. If someone wants to play as a doctor type preacher role that attempts to recruit from the ranks of factions then let them play that.

This is a perfect time to bring up the fact that a thing Fallout13 has always lacked is proper coordination of development. You could always get together with people and build up that other map that people were working on once upon a time that they never finished, and shove whatever handful of homebrew factions or whatever you want in there. 

That way you can avoid bloating your map faction rosters out so hard that at 90 pop the factions are void of life. A hypothetical win-win.

**Comment by SpaceSlug2** [comment]
> > Who cares if slots are filled? The point of factions are for peoples playstyles. If someone wants to play as a doctor type preacher role that attempts to recruit from the ranks of factions then let them play that.
> 
> This is a perfect time to bring up the fact that a thing Fallout13 has always lacked is proper coordination of development.
> 
> You could always get together with people and build up that other map that people were working on once upon a time that they never finished, and shove whatever handful of homebrew factions or whatever you want in there.
> 
> That way you can avoid bloating your map faction rosters out so hard that at 90 pop the factions are void of life. A hypothetical win-win.

Yeah this is mainly for the east coast map I heard was being made

**Comment by John-Dang** [comment]
> > > Who cares if slots are filled? The point of factions are for peoples playstyles. If someone wants to play as a doctor type preacher role that attempts to recruit from the ranks of factions then let them play that.
> > 
> > 
> > This is a perfect time to bring up the fact that a thing Fallout13 has always lacked is proper coordination of development.
> > You could always get together with people and build up that other map that people were working on once upon a time that they never finished, and shove whatever handful of homebrew factions or whatever you want in there.
> > That way you can avoid bloating your map faction rosters out so hard that at 90 pop the factions are void of life. A hypothetical win-win.
> 
> Yeah this is mainly for the east coast map I heard was being made

They especially shouldn't be all the way over on the east coast. Why would they be on the other end of the continent?

**Comment by Burtuu** [comment]
>defeated in fallout 1
>somehow still around in 2281

**Comment by hackerjsimon** [comment]
i like this idea

**Comment by SpaceSlug2** [comment]
> > > > Who cares if slots are filled? The point of factions are for peoples playstyles. If someone wants to play as a doctor type preacher role that attempts to recruit from the ranks of factions then let them play that.
> > > 
> > > 
> > > This is a perfect time to bring up the fact that a thing Fallout13 has always lacked is proper coordination of development.
> > > You could always get together with people and build up that other map that people were working on once upon a time that they never finished, and shove whatever handful of homebrew factions or whatever you want in there.
> > > That way you can avoid bloating your map faction rosters out so hard that at 90 pop the factions are void of life. A hypothetical win-win.
> > 
> > 
> > Yeah this is mainly for the east coast map I heard was being made
> 
> They especially shouldn't be all the way over on the east coast. Why would they be on the other end of the continent?

There were 2 mutant factions over at Washington D.C it would be logical for some COTC members to live and escape to Washington D.C and restart the church.

**Comment by SpaceSlug2** [comment]
> defeated in fallout 1
> somehow still around in 2281

It’s as illogical as the BoS having a entire surface area despite the NCR, and the Legion wanting to push their shit in

**Comment by Burtuu** [comment]
what is your discord

**Comment by John-Dang** [comment]
> > > > > Who cares if slots are filled? The point of factions are for peoples playstyles. If someone wants to play as a doctor type preacher role that attempts to recruit from the ranks of factions then let them play that.
> > > > 
> > > > 
> > > > This is a perfect time to bring up the fact that a thing Fallout13 has always lacked is proper coordination of development.
> > > > You could always get together with people and build up that other map that people were working on once upon a time that they never finished, and shove whatever handful of homebrew factions or whatever you want in there.
> > > > That way you can avoid bloating your map faction rosters out so hard that at 90 pop the factions are void of life. A hypothetical win-win.
> > > 
> > > 
> > > Yeah this is mainly for the east coast map I heard was being made
> > 
> > 
> > They especially shouldn't be all the way over on the east coast. Why would they be on the other end of the continent?
> 
> There were 2 mutant factions over at Washington D.C it would be logical for some COTC members to live and escape to Washington D.C and restart the church.

What mutant factions are you talking about? Are you talking about the mindless orks that are the east coast super mutants? That isn't a faction, that's a generic fantasy enemy that bethesda peppered their map with. Or the ghouls in Underworld? That's just a settlement, a village of ghouls holed up in the crumbling ruins of a museum because of persecution. Why would the cultists who followed the Master go all the way across post-apocalyptic North America, ignore everything from the west coast, to the midwest, until they reach Washington DC, which unlike the rest of the continent is just a pile of bricks and twisted metal, and then decide "ah yes, there are some super mutants that are nothing like OUR super mutants and just kill everything violently, here is where we will set up our new base of operations in honor of The Master and try his plan all over again" hm yes hm yes.

**Comment by SpaceSlug2** [comment]
> what is your discord

I don’t know why you’re asking but it’s Space Slug #7694

**Comment by Burtuu** [comment]
> > what is your discord
> 
> I don’t know why you’re asking but it’s Space Slug #7694

talk in devs general in the f13 discord

**Comment by SpaceSlug2** [comment]
> > > what is your discord
> > 
> > 
> > I don’t know why you’re asking but it’s Space Slug #7694
> 
> talk in devs general in the f13 discord

Still banned from the discord

**Comment by Burtuu** [comment]
> > > > what is your discord
> > > 
> > > 
> > > I don’t know why you’re asking but it’s Space Slug #7694
> > 
> > 
> > talk in devs general in the f13 discord
> 
> Still banned from the discord

then dont make prz

**Comment by SpaceSlug2** [comment]
> > > > > > Who cares if slots are filled? The point of factions are for peoples playstyles. If someone wants to play as a doctor type preacher role that attempts to recruit from the ranks of factions then let them play that.
> > > > > 
> > > > > 
> > > > > This is a perfect time to bring up the fact that a thing Fallout13 has always lacked is proper coordination of development.
> > > > > You could always get together with people and build up that other map that people were working on once upon a time that they never finished, and shove whatever handful of homebrew factions or whatever you want in there.
> > > > > That way you can avoid bloating your map faction rosters out so hard that at 90 pop the factions are void of life. A hypothetical win-win.
> > > > 
> > > > 
> > > > Yeah this is mainly for the east coast map I heard was being made
> > > 
> > > 
> > > They especially shouldn't be all the way over on the east coast. Why would they be on the other end of the continent?
> > 
> > 
> > There were 2 mutant factions over at Washington D.C it would be logical for some COTC members to live and escape to Washington D.C and restart the church.
> 
> What mutant factions are you talking about? Are you talking about the mindless orks that are the east coast super mutants? That isn't a faction, that's a generic fantasy enemy that bethesda peppered their map with. Or the ghouls in Underworld? That's just a settlement, a village of ghouls holed up in the crumbling ruins of a museum because of persecution. Why would the cultists who followed the Master go all the way across post-apocalyptic North America, ignore everything from the west coast, to the midwest, until they reach Washington DC, which unlike the rest of the continent is just a pile of bricks and twisted metal, and then decide "ah yes, there are some super mutants that are nothing like OUR super mutants and just kill everything violently, here is where we will set up our new base of operations in honor of The Master and try his plan all over again" hm yes hm yes.

Considering the year the Cathedral exploded the old Remnants of the Church went far away from any BoS or NCR and headed towards the Washington D.C - Chicago area and settled down opening up small churches and talk about the Unity until they start a small cult with around 50-100 people

**Comment by Mannybrado** [comment]
...you do know that that is literally across the entirety of america, right

**Comment by SpaceSlug2** [comment]
> ...you do know that that is literally across the entirety of america, right

You realized Lyons brotherhood fucking walked, right?

**Comment by John-Dang** [comment]
> > ...you do know that that is literally across the entirety of america, right
> 
> You realized Lyons brotherhood fucking walked, right?

Disregarding how ridiculous that was on its own, the shattered remnants of a cult who were ALL nuked and now have no members and no resources are in an entirely different place from a strong, well supplied militarized paramilitary cult.

**Comment by SpaceSlug2** [comment]
> > > ...you do know that that is literally across the entirety of america, right
> > 
> > 
> > You realized Lyons brotherhood fucking walked, right?
> 
> Disregarding how ridiculous that was on its own, the shattered remnants of a cult who were ALL nuked and now have no members and no resources are in an entirely different place from a strong, well supplied militarized paramilitary cult.

They have around 100 years to do that

**Comment by AdamElTablawy** [comment]
Let's be honest.

Realism isn't important. If it makes sense or doesn't make sense for it to happen is kind of irrelevant. Add whatever's fun and unique, not 'buh buh they were destroyed page 602 of my fallout bible says' because who the fuck cares? There's no logical reason for anyone to be in Yuma in the first place other than the Legion.

The problem with this is that it's just a barebones faction with barely anything going for it. It's just role bloat.

Do this as an outlaw or a wastelander rather than adding more job slots and factions.

**Comment by ogrigbe** [comment]
We do not need nor want any new factions at the current moment, keep this one in the back of your head, hold onto the PR and discuss with the dev team mainly including me before putting out a pull request.

**Pull request closed without merging**
