### PR TITLE
obliterates all chemical-based combat

### PR DESCRIPTION
**Pull request by dawsonkeyes**
chem nades and syringe guns have ceased to exist outside of like I think one map spawn in the clinic or whatever, they simply cannot be researched

finally

### CODE REVIEW

**Comment by Isy232** [comment]
I can understand syrine guns, they can be used to one shot people.

But chemistry grenades are fine, they've been nerfed to the point where they good but not insanely overpowered. If you think they're still overpowered, nerf some of the reagents again.

Removing them removes ways to make EMP grenades, ways to deal with overpowered defenses (see BoS).

**Comment by Lobachevskiy** [comment]
Better to balance chems and add counters to this (like face masks etc).

**Comment by KenrouSeimei** [comment]
It seems like a bit of a sweeping move when a portion of the playerbase utilize ghouls which aren't affected by gas, and there seems to be nearly no one who uses syringe guns. 

Perhaps you will not even observe one such player per day, maybe once a week or even then there is none. Its a literal afterthought. 

It also appears to target science based loadouts which do not have fancy guns or armor. Would it not be more sensible to simply increase the availability of respirators? Unless, this removal is aimed more at the explosive based chem nades.

**Comment by dawsonkeyes** [comment]
> It seems like a bit of a sweeping move when a portion of the playerbase utilize ghouls which aren't affected by gas, and there seems to be nearly no one who uses syringe guns.
> 
> Perhaps you will not even observe one such player per day, maybe once a week or even then there is none. Its a literal afterthought.
> 
> It also appears to target science based loadouts which do not have fancy guns or armor. Would it not be more sensible to simply increase the availability of respirators? Unless, this removal is aimed more at the explosive based chem nades.

this is entirely aimed at the constant use of gas grenades, medium explosives, and syringe guns by the bos but most especially the enclave, particularly in regards to the lack of outside balance. chem grenades remain an issue due to gas and foam permitting instant AOE distribution of death chems no matter your armor, and syringe guns also bypass all armor save solely for a power armor deflect. i shall not waver simply because enclave mains insist nobody uses these things when they’re abused constantly, and if nobody uses them, there’s nothing wrong with them leaving anyways 

¯\_(ツ)_/¯

**Comment by panzer1944** [comment]
Fine with the syringe gun yeet. Not-fine with the grenade yeet at all, very much so agreeing with Isy232 on this one - nerf / alter the reagents causing issues, not the entire system. Maybe re-add CUST0Ms explosive nerf which got reverted.

**Comment by KenrouSeimei** [comment]
> > It seems like a bit of a sweeping move when a portion of the playerbase utilize ghouls which aren't affected by gas, and there seems to be nearly no one who uses syringe guns.
> > Perhaps you will not even observe one such player per day, maybe once a week or even then there is none. Its a literal afterthought.
> > It also appears to target science based loadouts which do not have fancy guns or armor. Would it not be more sensible to simply increase the availability of respirators? Unless, this removal is aimed more at the explosive based chem nades.
> 
> this is entirely aimed at the constant use of gas grenades, medium explosives, and syringe guns by the bos but most especially the enclave, particularly in regards to the lack of outside balance. chem grenades remain an issue due to gas and foam permitting instant AOE distribution of death chems no matter your armor, and syringe guns also bypass all armor save solely for a power armor deflect. i shall not waver simply because enclave mains insist nobody uses these things when they’re abused constantly, and if nobody uses them, there’s nothing wrong with them leaving anyways
> 
> ¯_(ツ)_/¯

All I can say is I definitely should have tried being an enclave or BoS main earlier, ha! Didn't even know the bos used syringe guns or that syringe guns penetrated armor. Other servers had syringe guns not being able to penetrate armored clothing so I believed it was similar here.

**Comment by Isy232** [comment]
> Fine with the syringe gun yeet. Not-fine with the grenade yeet at all, very much so agreeing with Isy232 on this one - nerf / alter the reagents causing issues, not the entire system. Maybe re-add CUST0Ms explosive nerf which got reverted.

#48 was merged and not reveted, as the game is now explosives are nerfed

> All I can say is I definitely should have tried being an enclave or BoS main earlier, ha! Didn't even know the bos used syringe guns or that syringe guns penetrated armor. Other servers had syringe guns not being able to penetrate armored clothing so I believed it was similar here.

PA has the THICH_CLOTHING flag while other armours dont.

Even still, syringe guns can 1 shot gib people so maybe they deserve this.


That being said chemnades are interesting and for the most part not stupid OP, nerf reagents.

**Comment by Isy232** [comment]
@dawsonkeyes I have made another PR that addresses the problems you brought up in a more moderate way.

> this is entirely aimed at the constant use of gas grenades, medium explosives, and syringe guns by the bos but most especially the enclave, particularly in regards to the lack of outside balance

With everyone having access to them (albeit weaker versions) balance issues will become more apparent and be able to be squashed easier. Also the BoS/Enclave wont completely monopolize them.

> chem grenades remain an issue due to gas and foam permitting instant AOE distribution of death chems no matter your armor, and syringe guns also bypass all armor save solely for a power armor deflect.

I agree, syringe guns should be removed.

I also nerfed foam and smoke, they can still AOE distribute death chems, but with a much smaller AOE. No more flooding half of Oasis.

**Comment by ErwinSnowden** [comment]
Remove the Plant DNA Manipulator or you'll see people use botany for grenades instead. Otherwise, great PR.

**Comment by hackerjsimon** [comment]
literally a BOS buff in disguise

**Comment by hackerjsimon** [comment]
> Remove the Plant DNA Manipulator or you'll see people use botany for grenades instead. Otherwise, great PR.

bruh you didn't check code, separated chems doesn't exist so botany cant make bombs

**Pull request closed without merging**
