### PR TITLE
NCR's New Groove - Large Visual Overhaul

### PR DESCRIPTION
**Pull request by Dioclex**
## About The Pull Request

Hi, I'm Dioclex - did a lot of spriting on DR, including the massive overhaul of the NCR's headwear and uniforms. However, I was never quite satisfied with the work I did, and have now taken the opportunity to complete my vision for the NCR here on Fortune.
I believe that when approaching the NCR as a faction, it's important to try and get it as accurate to its in-game appearance and aesthetic as possible. As such, I've finished what I've started by completely redesigning all the NCR armour sprites, which I had always thought looked a bit shit. As well as returning to the traditional 'brodie' style helmets, as seen in-game, to deviate from DR's "alternate timeline" malarkey. I also redesigned the appearance of the berets, to essentially look better, little else to it. Furthermore I have fixed up a few visual errors with my old sprites, that I had never bothered to correct.

## Why It's Good For The Game

My general philosophy is that by bringing the NCR's appearance closer to how it appears in FNV, it will encourage players to immerse themselves more into the faction, and roleplay it closer to how the faction actually functions, rather than some confusing pseudo-US Army. This also ties in to the server's general direction with enhancing its Fallout-specific appearance, grounding it more within the canon. Obviously, everyone shares a certain level of affection for the non-canon Steelpot helmets, (I do too, I designed all the bloody variants for it), however, I believe that going for a more accurate appearance for the NCR is just generally better.

Feature

## Changelog
:cl:
add: NCR Medical Beret
tweak: All NCR Armours
tweak: All NCR Berets
tweak: Replace all Steelpot helmets with Brodie equivalents
tweak: Replace the original "storm" helmet, available to Sergeants, with the storm Steelpot Helmet
fix: Side sprites for the slouch hat

### CODE REVIEW

**Comment by SpaceSlug2** [comment]
Great! Now can you overhaul the IQ of the average NCR player?

**Comment by Dioclex** [comment]
> 
> 
> Great! Now can you overhaul the IQ of the average NCR player?

Only after I overhaul my own IQ to figure out what the fuck's wrong with my PR

**Comment by SpaceSlug2** [comment]
> Only after I overhaul my own IQ to figure out what the fuck's

I’ve been trying to figure that out myself for the past 3 hours. I think it’s some fucky code thing and I wouldn’t even worry about it

**Comment by Dioclex** [comment]
> 
> 
> > Only after I overhaul my own IQ to figure out what the fuck's
> 
> I’ve been trying to figure that out myself for the past 3 hours. I think it’s some fucky code thing and I wouldn’t even worry about it

Just tried something, that might fix it. If it does, I am _the_ hackerman.

**Comment by SpaceSlug2** [comment]
> > > Only after I overhaul my own IQ to figure out what the fuck's
> > 
> > 
> > I’ve been trying to figure that out myself for the past 3 hours. I think it’s some fucky code thing and I wouldn’t even worry about it
> 
> Just tried something, that might fix it. If it does, I am _the_ hackerman.

How'd you fix the run linters?

**Pull request merged**
