### PR TITLE
Fixes Chinese uniform item sprites

### PR DESCRIPTION
**Pull request by Sinbest**
## About The Pull Request

See above, I did the spriting for the new chinese uniforms so it was kind of my responsibility to fix em.

## Why It's Good For The Game

Anyone wearing chinese uniforms or just seeing them on the floor will no longer see mcdonalds priest hats and orange question marks.

## Changelog
:cl:
tweak: Fixes Chinese uniform item sprites
/:cl:

### CODE REVIEW

**Comment by ogrigbe** [comment]
Fix your conflicts and I will merge.

**Comment by Sinbest** [comment]
I can't find the one sprite that is making this conflict, I have looked for ages and ctrl c does nothing, you deal with it.

**Comment by Sinbest** [comment]
> Fix your conflicts and I will merge.

I can't find this goddamn head sprite, Ctrl C is broken and it isn't at the front like any normal person would put it, why is this my problem? This had no conflicts until other stuff was merged, that other request shouldn't have even been closed, hellfire power armor doesn't belong on the west coast

**Comment by Sinbest** [comment]
I TRIED TO FIX IT AND AHGGGGGGGGGGGGGGGGGGGGGGHDGHSGHYF

**Comment by Sinbest** [comment]
JUST FIX AND MERGE IT I AM IN PAIN

**Pull request closed without merging**
