### PR TITLE
Revert "Oasis tweak"

### PR DESCRIPTION
**Pull request by KillerGryphon**
Reverts nokele/Fortune13#316

Doing this at the request of Oasis players, who feel it has ruined the hard work done to revive oasis. We can't keep going back and forth. Pick an oasis and stick with it.

### CODE REVIEW

**Comment by Burtuu** [comment]
Also, JohnDang has even said that he is working on the issues with Oasis, this PR was rushed and uneeded, it's just a low-effort copypaste. 

> Alright so, I have another PR coming in to fix good issues brought up. I'm thinking of marking the mayor's house specially along with some other buildings. Think that's a good fix? Also yeah I should move em to the town hall perhaps. Aaand the church ladder's supposed to lead to the public soup kitchen.

**Review by John-Dang — APPROVED** [review]
God yes, please. I had already said I was going to put out a polished Oasis soon, that "tweak" chopped up all my work and it made me a little sick looking at all the copy paste and tearing up of the design. Yes, I approve. Please revert what they did.

**Comment by panzer1944** [comment]
Very much so prefer the tweaked oasis over the un-tweaked one - sure, some things have been pasted over from the old one, but it still feels mostly new to me and the layout is superior. Swapping back and forth is pointless, and I really dont think this PR needs to exist - if you want to make changes, just use the current version or make a PR with your full changes when it's ready, not stop-gap revert, leave everyone with the weird version and only then fix it.

**Comment by AdamElTablawy** [comment]
As far as I can tell the playerbase prefers the tweaked oasis.

**Comment by EgorDinamit** [comment]
> As far as I can tell the playerbase prefers the tweaked oasis.

Playerbase also prefered Enclave to stay, guess what: #324

**Comment by ThyBaron** [comment]
@EgorDinamit Please keep comments pertaining relevant information to the PR.

**Comment by ogrigbe** [comment]
We're going to stick with the current version of oasis.

**Pull request closed without merging**
