### PR TITLE
Lays the framework for a new faction replacing the Enclave

### PR DESCRIPTION
**Pull request by SpaceSlug2**
## About The Pull Request
It seeks to replace the Enclave with the Midwest chapter of the BOS seen in Fallout Tactics

## Why It's Good For The Game
Removing a faction without any replacements is brash and dumb I seek to replace the shittery of the Enclave with a superior faction.

## Changelog
:cl:
del: Removed the Enclave entirely from the code
tweak: Buffed the Midwest power armor
balance: Buffed the Midwest Power armor
code: Entirely changed the Enclave code
/:cl:

### CODE REVIEW

**Comment by SpaceSlug2** [comment]
I have no idea how any of this works. Could someone tell me how exactly to make it read a commit?

**Comment by Mannybrado** [comment]
Man WHY. WHY. Enclave DO NOT NEED to be replaced. I feel like I am going FUCKING INSANE.

**Comment by SpaceSlug2** [comment]
> Man WHY. WHY. Enclave DO NOT NEED to be replaced. I feel like I am going FUCKING INSANE.

I feel the exact same. But Baron isn't going to readd them so I might as well replace them

**Comment by BadAtThisGame302** [comment]
Don't replace them with anything, and surely not ANOTHER BoS Chapter

**Comment by AdamElTablawy** [comment]
enclave need to be reworked, not replaced, especially not by another faction that shares the exact same problems they do

**Comment by SpaceSlug2** [comment]
Yeah I agree with these people.

**Pull request closed without merging**
