### PR TITLE
buffs throwing spears to how they were back on BD

### PR DESCRIPTION
**Pull request by AdamElTablawy**
because it'll be really funny

guaranteed embed, somewhat decent damage, still a worse weapon than just shooting someone but now it's actually usable and will lead to funny deaths sometimes

## Why It's Good For The Game

fuck you

### CODE REVIEW

**Comment by ogrigbe** [comment]
I don't think so

**Comment by AdamElTablawy** [comment]
@ogrigbe why not, they're not overpowered 

considering you've merged far more bizzare in the past there's no reason to leave throwing spears completely useless as they are right now

it'll still take five throwing spears to down a target, and for each one you gotta pick it up and throw it-that's much harder than just clicking someone twice with an autoseared marksman carbine

**Review by EgorDinamit — CHANGES_REQUESTED** [review]
Do not merge this shit until someone fixes macros for throwing 10 spears in one click.

**Comment by AdamElTablawy** [comment]
> Do not merge this shit until someone fixes macros for throwing 10 spears in one click.

lol we still have macros?

**Comment by Mannybrado** [comment]
you can set your "pull from belt" keybind to the same as throw and rapid-shot out throwing spears because they dont have the throw delay like they used to

**Comment by EgorDinamit** [comment]
Yes. Add a throw delay and then we'd consider the buff to be a good option.

**Comment by AdamElTablawy** [comment]
where the fuck did the throw delay use to be @Mannybrado

**Comment by ogrigbe** [comment]
no thanks, add delay or go away. 100% embed = stupid people running around using them constantly killing everyone with dumb throwing spears.

**Comment by BigBigga** [comment]
Just parroting at this point, but yeah. No delay, no way. Plus, guaranteed embed is kind of stupid.

**Comment by AdamElTablawy** [comment]
i already said where the fuck is the delay thing so i can add it jfc

**Comment by ogrigbe** [comment]
I see no movement on this, so I close it for now.

**Pull request closed without merging**
