### PR TITLE
Changes the sprites of T-45 T-51 T-60

### PR DESCRIPTION
**Pull request by SpaceSlug2**
## About The Pull Request
I went to a old code source to add the old sprites back. It took about 10-15 minutes to do in total and look quite better in my opinion

## Why It's Good For The Game
Well the new T-45 T-51 T-60 doesn't even look like power armor more like a heap of scrap metal produced by cavemen

## Changelog
:cl:
add: Added the old T-45 T-51 T-60 sprites back
code: changed some code
/:cl:

### CODE REVIEW

**Comment by ogrigbe** [comment]
Do you have pictures for reference?

**Comment by SpaceSlug2** [comment]
> Do you have pictures for reference?

Give me like 2 seconds

**Comment by SpaceSlug2** [comment]
The helmet sprites for some reason are broken give me a couple of seconds to see why

**Comment by SpaceSlug2** [comment]
Right disregard this PR, the code is being a cunt and not changing the sprite

**Pull request closed without merging**
