### PR TITLE
Tribal Powercreep

### PR DESCRIPTION
**Pull request by Tokorizo**
Powercreep

### Reduces tribal numbers

(SAME) Chief 1 > 1
(SAME) Shaman 1 > 1
(SAME) Head Hunter 1 > 1
(SAME) Druid 2 > 2
**(NERF) Hunter 4 > 2**
(SAME) Guardian 2 > 2
**(NERF) Villager 4 > 3**
**(NERF) Pledge 3 > 2**

Reduces numbers of tribal population from 18 to 14

### Loadout changes

**(NERF) Reduces the number of all reinforced bolas by 2 to 1**
**(NERF) Guardian poultice is now regular powder**
**(NERF) Guardians spawn with Heavy Tribal armor instead of Razorclaw cloak**
(CHANGE) Chief spawns with Dclaw spear and no more Cleaving Saw

### Reduces and adjusts damage on spear weapons, 

**(NERF) Dclaw spear (20, 50) 0.4 AP > (20,45) 0.3 AP**
(BUFF) Impro glaive (8,30) 0 AP > (10,25) 0.1 AP (Reach is back)
(TWEAK) Bone spear (Same damage) 0.24 AP > 0.25 AP

## Why It's Good For The Game

Powercreep Powercreep Powercreep Powercreep Powercreep Powercreep Powercreep Powercreep Powercreep Powercreep Powercreep Powercreep Powercreep Powercreep Powercreep Powercreep Powercreep Powercreep Powercreep Powercreep Powercreep Powercreep Powercreep Powercreep Powercreep Powercreep Powercreep Powercreep Powercreep Powercreep Powercreep Powercreep Powercreep Powercreep Powercreep Powercreep Powercreep Powercreep Powercreep Powercreep Powercreep Powercreep Powercreep Powercreep Powercreep Powercreep Powercreep Powercreep 

Much weaker now, if it sucks ill tweak numbers again.

## Changelog
:cl:
tweak: powercreep
/:cl:

### CODE REVIEW

**Comment by Sinbest** [comment]
Hmm today I will remove half the slots of a faction that spends 90% of every round in their base because muh powercreep

**Comment by Tokorizo** [comment]
> Hmm today I will remove half the slots of a faction that spends 90% of every round in their base because muh powercreep

> Half the slots
what

**Comment by ProfessorPopoff** [comment]
While you're at it. You could remove the TG assets from them.

**Comment by Tokorizo** [comment]
> While you're at it. You could remove the TG assets from them.

nah

**Comment by Sinbest** [comment]
The Tribals spend almost every round in their camp, they almost never raid and are peaceful as fuck, why do so many people hate them

**Comment by EgorDinamit** [comment]
I agree with weapon nerfs, but if you're doing it, you might as well keep the slots.

**Pull request merged**
