### PR TITLE
Extra Quirks!

### PR DESCRIPTION
**Pull request by bardinatavern4**
Adds some new quirks for fun & flavor

- Cannibal, which makes the person who has it enjoy human based foods. Also makes it so that when they consume "Longpork Stew" a new craftable item, it heals them slightly. If you don't have the cannibal quirk it adds toxin damage. 
- .
- Former Tribal, which gives you technophobe and the machine spirits traits. What this means is you can't use autolathes or chem machines, but get the benefits of better bitter drink. You can still use reloading benches, but that's it.

-Split Personality. Does what it says on the tin. Gives you split personality as an unremovable big negative,

-Imaginary Friend. Does what it says on the tin. Gives you an unremovable split personality.

### CODE REVIEW

**Comment by dawsonkeyes** [comment]
Does the Cannibal perk have any actual downsides? It sounds like a complete and total buff that anyone should take for the sake of another food source and free healing.

**Comment by bardinatavern4** [comment]
There are other purely positive quirks, and it costs 3 points which is the same as Lifegiver used to be. It's not very strong since you need to find someone and kill them for a worse healing powder.  Also most factions will execute you if they find out. Overall while it is a positive, it requires you to have a few negative traits and is minorly strong if anything. Do note it  stack with powder or stimpaks as well.

**Comment by dawsonkeyes** [comment]
> There are other purely positive quirks, and it costs 3 points which is the same as Lifegiver used to be. It's not very strong since you need to find someone and kill them for a worse healing powder. Also most factions will execute you if they find out. Overall while it is a positive, it requires you to have a few negative traits and is minorly strong if anything. Do note it stack with powder or stimpaks as well.

Sorry, pardon me, I was under the impression it was one of the neutral traits

**Comment by hackerjsimon** [comment]
cant find in game oof

**Pull request merged**
