### PR TITLE
Adds "Enclave remnant" loadout to Outlaw; Replace T-60 with X02 in the Enclave bunker.

### PR DESCRIPTION
**Pull request by EgorDinamit**
## About The Pull Request

Everything's in the title. Adds a small loadout to outlaws that has .22 pistol, old peacekeeper uniform, T3 battle coat and a "holo dogtag".

Replaces T-60 with Enclave power armor in that one bunker with Enclave NPCs and "Frank Horrigan".

Sets Enclave PA tier to 11, as it is stated in the description.

## Why It's Good For The Game

#324 : A small fluff thing to have until we bring Enclave back.

T-60 has the same armor values as X02. Now that Enclave is temporarily disabled there is no way to get X02 without admins. It is also an Enclave bunker, I don't see a reason to keep T-60 in there.

It seems that there was a mistake when someone coded it. The description clearly says "XI", not "X".

## Changelog
:cl:
add: Added "Enclave remnant" loadout to Outlaw role.
tweak: T-60 in a bunker with Enclave NPC is replaced with Enclave power armor.
tweak: Enclave power armor is now tier 11, just like description was always saying.
/:cl:

### CODE REVIEW

**Comment by SpaceSlug2** [comment]
First of all... What's the point of the outlaw loadout?

**Comment by EgorDinamit** [comment]
> First of all... What's the point of the outlaw loadout?

You've been a part of the Enclave in the past and you've been keeping some of the stuff with you.
Literally the same point as every other loadout.

**Comment by SpaceSlug2** [comment]
> > First of all... What's the point of the outlaw loadout?
> 
> You've been a part of the Enclave in the past and you've kept some of the stuff with you.
> Literally the same point as every other loadout.

my bad man I learned a little while ago non-based staff team removed enclave without caring about the vote

**Comment by EgorDinamit** [comment]
> > > First of all... What's the point of the outlaw loadout?
> > 
> > 
> > You've been a part of the Enclave in the past and you've kept some of the stuff with you.
> > Literally the same point as every other loadout.
> 
> my bad man I learned a little while ago non-based staff team removed enclave without caring about the vote

Even if Enclave is back, this loadout could be fun to use, maybe even rename it to a "Enclave Deserter", or leave it open to the player's interpretation.

**Pull request merged**
