### PR TITLE
i dont like conflicts

### PR DESCRIPTION
**Pull request by Tokorizo**
## About The Pull Request

attempt number 3 of https://github.com/nokele/Fortune13/pull/315

## Why It's Good For The Game

third times the charm

## Changelog
:cl:
del: remove sneedclave
/:cl:

### CODE REVIEW

**Comment by Burtuu** [comment]
it isnt going to get through, the vote was sealed.

**Comment by BadAtThisGame302** [comment]
Stop hating democracy and close this down

**Comment by thedarkcrusader** [comment]
You want to see the profits of democracy? Then go and see 'em
Across the street, a bunch of freaks are playing Colosseum
Honestly? Was the world you wanted what you got to see?
When you were dropping crosses into boxes behind polling screens?
Was dropping bombs your chosen option? Did you vote for screams?
Was the apocalypse your politician's policy?
Did you put stock in their prepostering and prophesy?
A shining future built on squabble-free equality?
That every day you'd get your plate of steak and collard greens?
That the human race was capable of anything but wanton greed?

**Comment by Singularity69** [comment]
renaming your PR to avoid controversy smh

**Pull request merged**
