### PR TITLE
Enclave Bunker remap.

### PR DESCRIPTION
**Pull request by Mannybrado**
## About The Pull Request
Completely remakes the enclave bunker. The previous one was very small, ugly, and made no sense as an actual location whatsoever. This fixes at least two of those three issues.

## Why It's Good For The Game
Map.
enclave

## Changelog
:cl:
add: Added new 
del: old
/:cl:

### CODE REVIEW

**Comment by DeveloperLoser** [comment]
Not a _huge_ fan of the chem setup, but far better than what I can do.

**Comment by panzer1944** [comment]
Looks good. I approve.

**Comment by Mannybrado** [comment]
actually i agree that the chem setup sucks. i just copied it over directly but i'll fix it.

**Comment by Mannybrado** [comment]
image
new infirmary

**Comment by DeveloperLoser** [comment]
I hate to do this but I'm gonna merge conflict you to, but should be able to resolve them almost immediately if it does freak out.

**Pull request closed without merging**
