### PR TITLE
BoS loadouts changes + new melee weapon

### PR DESCRIPTION
**Pull request by PhoronRestructurantHuman**
Tried to ask around in the community as much as I could for suggestions and changes, especially the Brotherhood Mains.

## About The Pull Request
Loadouts mostly changed, new weapon added (Pre-war military ripper) and new armor stats that doesn't make every knight into a mini-veteran ranger.
Head Paladin: (Tribeam, Rangemaster, Gauss+Glock, Gatling)
Head Knight: (AER14, Marksman, Neostad)
Senior Knight: (RCW, Police Shotgun)
Senior Paladin: (AER14, Marksman, Pre-war military ripper + Big Leagues)
Paladin: (AER12, R91)
Knight: (AER9, R82)

The new armors are as following;
Initiate T4
Knight T5
Head/Senior T6

The new ripper is pretty much a reskinned ripper with both AP and more damage. (It'd take about 8 hits to kill another paladin)
image

## Why It's Good For The Game
Brotherhood kits has been very neglected, they've completely lacked any attention which was apparent by their 4 glocks and G11. I've tried to make the kits a bit more interesting while still nothing making them bad. I added a new rather powerful melee weapon for the senior paladin, I added a ballistic option for the head paladin and I've tried putting a general theme with a non-lethal option for knights (Beanbag shotguns). The armor was just general powercreep, a knight has the same armor as the veteran ranger so I brought it down, now a knight/initiate will be around or above the same level as a ranger.

## Changelog
- Made sure to properly adjust the helmets, made the craftable BoS armor actually make sense statwise and made a new "reinforced knight armor" for the reinforced combat armor. I bandaided a issue that allowed for you to craft normal combat armor from reinforced combat armor. A total noob-trap with no real reason to exist, but I couldn't properly fix it without shitcoding 500 lines of blacklist to the crafting so instead my next PR will (probably) be trying to seperate MK2 and it's subtypes from it's parent (combat armor) without breaking anything. That way crafting won't be scuffed as fuck, (hopefully) Or I'll just try to work on some sort of overlay system.
- Decided to give Paladins a rifle instead.

### CODE REVIEW

**Comment by dawsonkeyes** [comment]
VERY GOOD COMRADE I RATE TEN OUT OF TEN YES YES GOOD VERY I WANT SEE MORE OF YOU WORK

**Comment by AdamElTablawy** [comment]
Remove the head scribe's energy shield.

**Comment by PhoronRestructurantHuman** [comment]
> Remove the head scribe's energy shield.

	- /obj/item/shield/energy=1, \

I did, it was in his backpack.

**Comment by dawsonkeyes** [comment]
I do however suggest that you remove the recipe turning normal combat armor to Brotherhood initiate armor, as the tiers are no longer equal (not that it made sense in the first place)

**Comment by PhoronRestructurantHuman** [comment]
> I do however suggest that you remove the recipe turning normal combat armor to Brotherhood initiate armor, as the tiers are no longer equal (not that it made sense in the first place)

Yeah, I'll do that and change the helmets because I forgot to.

**Pull request merged**
