### PR TITLE
Syringe gun removal

### PR DESCRIPTION
**Pull request by ErwinSnowden**
## About The Pull Request

Not a lore friendly weapon.
Not a balanced weapon.

## Why It's Good For The Game

This should have never been added to "medical weaponry". Whoever did it years back should've had some foresight that syringe guns are badly balanced, especially with superOD chems like Med-X.

## Changelog
:cl:
del: The syringe gun is no longer printable.
/:cl:

### CODE REVIEW

**Comment by BadAtThisGame302** [comment]
https://fallout.fandom.com/wiki/Syringer_(Fallout_4)

**Comment by panzer1944** [comment]
> https://fallout.fandom.com/wiki/Syringer_(Fallout_4)

Contrary to the syringer, the current one he is trying to remove is an ez-to-spam rapidfire any-chem monstrosity, not a 1shot then need reload weapon with a limited array of syringes that doesnt include broken op ones, which the one he's removing can utilize.

**Comment by BadAtThisGame302** [comment]
instead of removing it you could nerf it

**Comment by panzer1944** [comment]
> instead of removing it you could nerf it, for example the fire rate and the syringe capacity

literally just encourages people to use the funny chloral hydrate meme-gun by it simply existing. It's existence encourages a method of combat only 2 factions are capable of which completely destroy any chance of any other faction winning unless they carry epi and charcoal everywhere, which most people dont nor should they.

**Comment by Isy232** [comment]
Nerf the mega OD chems or something, syringe guns are cool

**Comment by AdamElTablawy** [comment]
no, the removal's good

**Comment by ErwinSnowden** [comment]
not at all aware why integration tests isnt working since it compiled for me, will re-open later when i can figure this out

**Pull request closed without merging**
