### PR TITLE
Feral ghouls attack Normal ghouls

### PR DESCRIPTION
**Pull request by panzer1944**
## About The Pull Request
In spite of the 6 commits shown (because i forgot to update my fork and some other shit), only one word is actually changed - the faction "Ghoul" to "Hostile" for feral ghouls as to completely eradicate the cheese ghoul players get. No, this PR doesn't fix the fact ghouls are auto-assigned a no-breathing trait, just fixes the ferals.
## Why It's Good For The Game
Anti-cheese, stops ghouls from having to put in 0 effort by just dragging around a glowing ghoul and legendary ghoul wherever they wanted to kill something.
## Changelog
- Changes literally one word
image

### CODE REVIEW

**Comment by Tokorizo** [comment]
kinda kills the whole, uniqueness of being a ghoul

**Comment by dawsonkeyes** [comment]
> kinda kills the whole, uniqueness of being a ghoul

you mean the radiation immunity/healing and lack of breathing doesn't??? fuck off dude

**Comment by Sinbest** [comment]
This isn't lore friendly, at all, ferals not attacking normal ghouls is a established part of Fallout lore, you can't just get rid of it because 'muh cheese'

**Comment by panzer1944** [comment]
closed so i can get new pr yes

**Pull request closed without merging**
