### PR TITLE
G11/e Rebalance

### PR DESCRIPTION
**Pull request by Isy232**
## About The Pull Request

Normal G11 slightly buffed.
G11e nerfed. Its no longer a minigun.

Specific:
G11 rounds from 42 damage to 37 damage, equal to 5.56 FMJ

Normal G11 gets burst fire, increased its fire delay to match that of the assault carbine.
Now its an assault carbine with printable 50 round mags, more accuracy and a free scope.

G11e fire delay increased to be slightly lower than G11/Assault Carbine.

## Why It's Good For The Game

Without even needing tinkering the G11e was capable of being basically a minigun and its rounds did more damage per shot than 5.56. Its extremely overpowered and perhaps even the best gun in the game pre-tinkering. This makes it more reasonable to the point where its quite a bit better than the assault carbine, but not godly OP.

Also buffs the normal G11 so thats its a decently good gun.

## Changelog
:cl:
balance: G11e nerfed, G11 buffed.
/:cl:

### CODE REVIEW

**Comment by dawsonkeyes** [comment]
This is great and all, but it ignores the other existing guns with similar power, namely the almighty unbeatable tommygun with it's initial burst of 4 rounds and insane firepower. Why?

**Comment by Isy232** [comment]
> This is great and all, but it ignores the other existing guns with similar power, namely the almighty unbeatable tommygun with it's initial burst of 4 rounds and insane firepower. Why?

I'm here just to fix one broken gun, not rebalance the whole game.

Maybe if I die to this tommy gun BS you mention I'll get pissed enough to make another salt PR.

While this is a salt PR, the G11e is undoubtedly extremely overpowered and the normal G11 is so shit a pistol you find in the trash is probably better.

**Comment by dawsonkeyes** [comment]
both G11s are burst fire and use the same ammo, the different is a tiny bit of fire rate and spread dude, you've clearly never used the og G11 in comparison

**Comment by Isy232** [comment]
#144

**Pull request closed without merging**
