### PR TITLE
Yuma Central Hospital

### PR DESCRIPTION
**Pull request by Mannybrado**
## About The Pull Request
Adds in a new location: The Yuma Central Hospital. Big place with lots of medical stuff.
image

## Why It's Good For The Game
There isn't a proper medical loot location, now there is. I might expand it further later on if someone wants me to.

## Changelog
:cl:
add: hospital
/:cl:

### CODE REVIEW

**Comment by Mannybrado** [comment]
added in lights

**Comment by VEN0M5** [comment]
Where is the chem heater?

**Comment by Mannybrado** [comment]
added

**Comment by VEN0M5** [comment]
No IV drips? Why is the sleeper room even blocked off by tables? I don't think the bot will do that and it certainly is not the original hospital arrangement. I think you misplaced the tables as the loot is spawning on the floor

**Comment by Mannybrado** [comment]
its... meant to be that the guy in there grabbed a robot, barricaded and pushed the table against the door. then died for some reason. forgot IV drips.

**Comment by VEN0M5** [comment]
> its... meant to be that the guy in there grabbed a robot, barricaded and pushed the table against the door. then died for some reason. forgot IV drips.

Oh I missed the bones in the room, guess I am blind

**Comment by EgorDinamit** [comment]
Mmm yes, now every single piece of equipment is lootable without any player interactions. Fun....

I'd say remove sleepers and replace old-world chem masters with normal ones.

**Pull request merged**
