### PR TITLE
Minor Dungeon Tweaks

### PR DESCRIPTION
**Pull request by dawsonkeyes**
- Changes gunslinger power armor in north sewers to T-45d
- Makes Enclave bunker a tiny bit harder
- Adds inside joke
- Updates Arlem's drip (seen below)
image

### CODE REVIEW

**Comment by Isy232** [comment]
> Changes gunslinger power armor in north sewers to T-45d

I like everything else but why remove the gunslinger PA. Its a really cool looking set and there isn't any way to cheese the dungeon its in to get it. It only opens up at 1 hour into the round and to get it you need to kill:
~15 raiders
~5 legenary raiders
5 salvaged turrets
3 assaultrons
1 sentry bot
4 gutsy's
~3 protectrons
3 deathclaws
1 legendary deathclaw
1 deathclaw nest

Maybe if you do all this you deserve a set of bad ass looking PA?

**Comment by dawsonkeyes** [comment]
> > Changes gunslinger power armor in north sewers to T-45d
> 
> I like everything else but why remove the gunslinger PA. Its a really cool looking set and there isn't any way to cheese the dungeon its in to get it. It only opens up at 1 hour into the round and to get it you need to kill:
> ~15 raiders
> ~5 legenary raiders
> 5 salvaged turrets
> 3 assaultrons
> 1 sentry bot
> 4 gutsy's
> ~3 protectrons
> 3 deathclaws
> 1 legendary deathclaw
> 1 deathclaw nest
> 
> Maybe if you do all this you deserve a set of bad ass looking PA?
> Its got 300 of each armour, its good but not godly or anything.

It's equal to T-45d, and looks like actual shit. It's a really old sprite. Furthermore, it was commissioned by someone long ago on a server long ago, and I'd rather not make use of such a particular thing.

**Comment by panzer1944** [comment]
Hi. As the person who made the dungeon in question, alongside all its difficulties and the likes, T-45d in the current balance of Fortune 13 doesn't really cut it for the bunker. Gunslinger cut it simply due to it being a unique set akin to T-45d but without slowdown. Maybe replace it with edited X-02 or something since X-02 is on par with T-51b currently

**Comment by dawsonkeyes** [comment]
> Hi. As the person who made the dungeon in question, alongside all its difficulties and the likes, T-45d in the current balance of Fortune 13 doesn't really cut it for the bunker. Gunslinger cut it simply due to it being a unique set akin to T-45d but without slowdown. Maybe replace it with edited X-02 or something since X-02 is on par with T-51b currently

I'm going to change it to the standard Tier 5 armor spawn as is per regular with difficult dungeons with power armor rewards (North Bunker, Southwest Bunker, Vault Dungeon, Enclave Bunker is an outlier for it's unique difficulty)

**Comment by dawsonkeyes** [comment]
I also want to point out that it's intended reward when it was unused in the files was a suit of T-45d, so, hey, you sure you "made the dungeon", or did you just take it outta the files?

**Comment by panzer1944** [comment]
> I also want to point out that it's intended reward when it was unused in the files was a suit of T-45d, so, hey, you sure you "made the dungeon", or did you just take it outta the files?

It's intended reward was a suit of T-45d power armour for DR, yeh, because PA is much rarer outside of the BoS there. This is not DR however, and PA is much more common.

**Comment by dawsonkeyes** [comment]
> It's intended reward was a suit of T-45d power armour for DR, yeh, because PA is much rarer outside of the BoS there. This is not DR however, and PA is much more common.

....and the suit is literally statistically equal to T-45d. So, I changed it to a Tier 5 armor spawn, meaning it can spawn either T-45d or T-51b. All's good either way.

**Pull request merged**
