### PR TITLE
NCR Loadout Reworks 2: Trench Raider boogaloo

### PR DESCRIPTION
**Pull request by bardinatavern4**
NICE_SHOT trait has increased bonus to ricocheting bullets, making it more effective (this becomes relevant later)

Trait granter for NICE_SHOT added

Crafting recipes for a nerfed landmine was added (light explosion + shrapnel, does around 20 damage but blinds you)

Blueprint that gives punji stick + landmine recipe added

variable that makes a specific gun untinkerable added

variable that makes an ammobox unloadable added

SSGT and Off-Duty given 0 spawn slots, roles effectively moved to SGT and Rear-Echelon via loadouts.

5 new weapons including:

The M2 Flamethrower. Does very little burn on hit, but sets the target on fire with 4 fire stacks, little bit less then a flame arrow. Overheats very quickly, has a long fire delay, and requires your back slot, but should give good crowd control. 

The accurized hunting rifle, basically just a 7.62 hunting rifle for first recon roles. Pen is 0.05 higher then mosin nagant, longer fire delay and same damage. 

M1/N carbine. Nerfed version of the M1 Carbine that can't take an autosear or be tinkered. Has 2 more damage to slightly make up for it, but still generally worse.

Destroyer Carbine, a commando carbine that comes autoseared by default but can't be tinkered or upgraded further.  Has as lightly longer fire delay. An actual commando carbine, upgraded, is better but since this can spawn by default it needs to be worse.

The QSP, based off the vietnam era quite special purpose revolver that fired a shot of tungsten balls. Replacement for the Sequoia for vet, does less damage on direct hit but does more if you manage to bounce the shot then hit someone.  Vet gets a traitbook with it to increase his ricochet stats. Should be a high skill high reward weapon, being worse then the sequoia unless you can consistently land bounces. Fire rate is lower and the ammo type is advanced meaning you need a tier 4 book to get more ammo. This was a pain in the ass to code.

A single piece of armor was added, which is just a tier IV first recon beret for some of the marksman roles. 

The following roles were added using all of the shit there:

Sergeant - 

Trench Raider 
Trench shotgun, trench knife, gas mask, and smoke grenades. Spread the word spread the word over thereeee. Do note the 
trench shotgun both got nerfed recently and  magnum buck got removed. It's not same crazy death machine it used to be.

Pathfinder Squad Leader
Paratrooper foldable M1 and hard yards book, meant to lead squads of the pathfinder loadout from trooper.

Rifleman
aka basic sergeant.

Corporal -

Designated Marksman. 
Gets the before mentioned accurized hunting rifle. Very slightly higher damage per shot then a sniper rifle, much slower fire rate and bolt action. Also gets a first recon beret though the stats have been nerfed to IV.
Spotter 
Scout carbine and binos. Meant to act as a spotter for designated marksman or a scout within a squad. The scout carbine is basically a nerfed service rifle so nothing out of place here.
Rifleman
Default corporal loadout. Service rifle and some mags.

Combat Engineer -
Construction Specialist
Just default engineer, nothing to see here folks.

Trapper
Gets the punji sticks and landmines recipe. Landmines do about 20 damage but send out shrapnel and blind you. They're also pretty easy to spot, but could be good at putting along fences to delay enemies breaking in. I see them being a niche tool since they're so easy to disable. Punji sticks are also nice. Gets less building resources then construction specialist.

FLAMMMMMMMMMMMETHROWER
Gets the flamethrower, but loses all construction materials and tools. Flamethrower does very little damage on hit, overheats quickly, and requires a cooperative chemist making you napalm to refuel. In testing, me and Diedsniper found that if someone just rushes you after you set them on fire you'll basically always die to them, and they'll be able to put themselves out in one or two rolls, making this a poor weapon for 1v1s but good in large battles where you have team mates pushing.

Rear Echelon got an off duty role. Nothing much to say about it. They get their lunch that their mom packed them.

Vet Ranger CQC loadout was replaced. Instead of a R91 they now get a 2 round burst commando carbine. DPS wise the R91 is notably better against armored targets, but the commando carbine has higher raw damage. Can't be tinkered or modified.
They also get what was the 2nd hardest weapon to make for this PR after the flamethrower, the QSP. In the hands of a random wastelander the QSP is a decent but not exceptional weapon. With the NICE_SHOT trait that comes with this kit though, the QSP is on par with the Sequoia. It fires a cloud of 6 pellets, each dealing less damage then regular buckshot. HOWEVER on a bounce, they all get 1.3x more damage, making it equal to buckshot then inbetween buck and magnum on second bounce. NICE_SHOT trait makes it so the vet will always get 2 bounces from the pellets, and people standing nearby and within around a 50 degree angle will get the bounce to home in on them. On a direct hit, it does notably less damage then a sequoia, but in the hands of someone who really practices with the gun it should be better in urban environments where you can get 1 or 2 bounces and then land the pellets on someone. I'm really excited to see this in game, it should make for a very cool and unique weapon that rewards getting very skilled at ricochets. Me and diedsniper spent a lot of time tuning the stats to get it around Sequoia equivilent without being better, it might still need tuning though. 

SSGT was given 0 spawn splots and effectively moved to other roles

Finally, trooper has it's service rifle replaced with a varmint rifle. With a lot more slots for solid frontline combat roles like corporal or sergeant or flameengineer, NCR has the firepower it needs. Service rifles aren't that hard to craft and they're also right about to get buffed. Reducing troopers to a varmint rifle should encourage them to get out of base and prevent the NCR from having an overwhelming amount of firepower, instead more spread out throughout the ranks unless they spend the time and resources upgrading everyone.
Their M1 carbine was also replaced with the M1/N, which can't be tinkered or autoseared.

### CODE REVIEW

**Comment by bardinatavern4** [comment]
Checks came back clear, and me and Diedsniper bugtested this within an inch of it's life before the PR went up. Should be clear to merge.

**Comment by Pebblesthe2nd** [comment]
The good:
Removing off-duty and staff sgt is a good call, the NCR role bloat needed sorting.
The new vars for blocking tinkering and unloading boxes is great, I really love useful functions like that, literally no downside to 
having that tool around.
Varmint rifle for troopers good, gradually shifting towards lower end guns should be the goal for all loadout overhauls currently.

The bad:
12 commits, 31 files, adding brand new potentially very powerful things like flamethrowers and landmines and punjis, NCR exclusive. Stuff added and not mentioned in the comments: new 10mm ammo type, QSP tungsten pellets, and a QSP revolver, new hunting rifle version with 7.62 and some minor stat changes. No changelog at all. Its basically unmergable in this state. The flamethrower alone needs its own PR to be honest, so it can be tested by others.

**Comment by bardinatavern4** [comment]
>  Stuff added and not mentioned in the comments: new 10mm ammo type, QSP tungsten pellets, and a QSP revolver, new hunting rifle version with 7.62 and some minor stat changes. No changelog at all. Its basically unmergable in this state. The flamethrower alone needs its own PR to be honest, so it can be tested by others.

It was late at night and the QSP got added after the initial PR was made. For the record 10mm QSP ammo only works in the QSP, it's not a new ammo type for 10 mils.
>No changelog at all.
read the first post, the changes are documented there

**Comment by Pebblesthe2nd** [comment]
The changelog is the automated part on the bottom, between the CL hashmarks. Its been removed in this PR. It saves the information you put into the categories to the logs so its possible to track issues in the future. The PR text is just the presentation to the maintainer more or less, the changelog is just as important, since searching for stuff in VSC brings up logs but not PR text on github. See other PRs and you will notice how the changelog should look.

In general its not a great idea to mix wildly different additions in one messy PR, in this case, the new guns could be made into its own PR and the loadout stuff in another, making it easier to overview. You made two new commits tweaking after your last comment, for example, obviously you are finding some new stuff still.

Trust me, I know messy PRs, I've done a few in my days, and it's not good practice, there is literally zero need to do the flamethrower, QSP and mines in the same one as the loadouts, it just causes possible issues. 

Also I might be hallucinating but it looks like the gun inhand files are removed by this PR.

**Comment by bardinatavern4** [comment]
The .DMIs thing is a bug with github, they're fine.

**Comment by dawsonkeyes** [comment]
pretty cool stuff but by god the qsp is the greatest idea ever made
the vet can now properly revolver ocelot shots at people

**Pull request merged**
