### PR TITLE
Using matrix and ladders is now not instant.

### PR DESCRIPTION
**Pull request by EgorDinamit**
## About The Pull Request

Ladders and Matrix now have a delay before activating their effects.

## Why It's Good For The Game

Ladders were actively being used to abuse simple_mob AI and cheesing it, mostly in places like Casino.
Not only it was used against simple mobs, it was also being actively used in battles that so happened to take place near ladders; Places like NCR basement, and BoS bunker entrance.

Matrix had a similar issue. Some people were seen using matrix during raid or combat to escape it.
The delay will make sure that they can't escape unnoticed.

## Changelog
:cl:
tweak: Using ladders and matrix now have a small delay.
/:cl:

### CODE REVIEW

**Comment by SquishyOranges** [comment]
No.

**Comment by Singularity69** [comment]
No

**Comment by SpaceSlug2** [comment]
No

**Comment by Robloxcumlord** [comment]
No.

**Comment by EgorDinamit** [comment]
> No.

Explain why or perish.

**Comment by Robloxcumlord** [comment]
> > No.
> 
> Explain why or perish.
> 
> By the way, the ladder delay is only 1 second.

its cringe.

**Comment by EgorDinamit** [comment]
> > > No.
> > 
> > 
> > Explain why or perish.
> > By the way, the ladder delay is only 1 second.
> 
> its cringe.

So you just want to abuse ladders, gottcha.

**Comment by Singularity69** [comment]
> Explain why or perish.

delay for using matrix is dumb. it's for people wanting out of a round

**Comment by Robloxcumlord** [comment]
> > > > No.
> > > 
> > > 
> > > Explain why or perish.
> > > By the way, the ladder delay is only 1 second.
> > 
> > 
> > its cringe.
> 
> So you just want to abuse ladders, gottcha.

Cry about it.

**Comment by ThyBaron** [comment]
Hello! Thank you for putting in the time to formulate this change! This is a change we'd certainly seek to implement.

**Pull request merged**
