### PR TITLE
The Great Raider Awakening

### PR DESCRIPTION
**Pull request by bardinatavern4**
So previously, there used to be two raider towns on the map that barely got used. Normally it didn't get much pop and me an some others talked about it. After talking about it, I then spent like 6 hours coding/mapping in order to add a new raider settlement to the map and encourage players to use it.  This would benefit the server by both adding another active settlement to RP in, and getting outlaws to actually know eachother and interact with eachother beyond just escalation gimme all your money. When in the town outlaws are encouraged to stop, have drinks with eachother, and form gangs together before going outside. The Den itself, as a result of the large khan presence, will be in a constant power struggle between the Boss running the Den, the Khans, and outlaw gangs who all want control. This should lead to a lot of interesting RP opportunies and massive  gang wars within the sewers. The rundown is this:

The barely used khan raider town has been scrapped and turned into a massive minable mountain.
The sewer raider town that never got used has been completely revamped and turned into a small sewer settlement called "the Den". Filled with trash, blood, guts, and waterways, it's run by the Den Mob. 

The Den Mob has been added, since someone has to have access to the gate button and actually administer the town. To minimize role bloat, only two roles were added. Den Boss, and the Enforcers. The Den Boss gets access to good armor and a thompson, along with a specialized gang tool that lets them (eventually, at over 1000 caps price) buy raider PA and other goodies. The Enforcers get their choice between a trench shotgun, as silenced uzi, or a type 17 10mm pistol and a chem book. Not terrifically strong but a little bit better armed then your average raider.

The khans have been moved into a bar called "Little Red Rock" inside the Den, complete with fight pit and farm. This gives them a permanent settlement to base around and help eachother out in, as well as a reason to want to take it over from the Boss.

All outlaws now start their round in The Den to encourage them to stop and seek out others to RP with or work together with on their escapades.

It's kind of hard to show but the new Den, while small, is pretty extensive in features. It has it's own shop, hotel, garage, bar, and headquarters for the Den Mob. 

The basic laws of the Den are as follows: No killing eachother while inside, no stealing while inside, pay tribute to the Boss. This is to encourage outlaws/khans to actually seek conflict with them instead of just forming a massive murderball of outlaw gangs. The Boss is *not* their friend and will make them pay tribute so long as he rules the Den.

Overall this should lead to some really interesting roleplay opportunities, gang wars, get outlaws to actually RP with eachother more, and add an active settlement for people who want to RP.

One issue is that by adding a settlement in the middle of the sewers, it means the walls will block off certain tunnels. A player reaching one of these dead ends might be annoyed, after all they used to know where to go and now there's a wall in the way that wasn't there before. In response this, I've put signs at the dead ends saying "Fuck Off". 

The PR was tested pretty extensively on my end to troubleshoot for bugs in advance, though there might still be some.

### CODE REVIEW

**Comment by Mannybrado** [comment]
so fresh so clean

**Comment by AdamElTablawy** [comment]
a THOMPSON.

No, that's ridiculous. A thompson is obscenely powerful. Downgrade the gun to something more manageable, like a brush gun.

**Comment by bardinatavern4** [comment]
Should be good to merge now.

**Comment by Keksk** [comment]
The new outlaw/khan base is now a lot smaller than the previous one but I don't think that'll be an issue.  It's a nice change!
The only annoyence I can find is in this little corner that could be an easy fix. They also have quite a lot of resources in their spawn that might need to be toned down like the 160 sheets of leather and the 25 crafting spawner.

grafik

grafik

**Comment by bardinatavern4** [comment]
[Corner's fixed](https://gyazo.com/494212cadca45fa30d4ed28405b934e5)
Leather was reduced to 20, crafting components to 10.

**Comment by bardinatavern4** [comment]
Alright! Short of bug fixing this should be the the final commit. I made the Den slightly bigger to add a couple more subway tunnels and back areas for flavor, since before it felt kinda tiny. A preacher's hut, interrogation room for the Mob, gallows for those who break the Den rules, etc.

**Pull request merged**
