### PR TITLE
Enclavophobia

### PR DESCRIPTION
**Pull request by EgorDinamit**
## About The Pull Request

Adds Enclavophobia. Phobia of Enclave stuff.

## Why It's Good For The Game

Funny admin-only phobia that you can give out to shitters; Usually to those who metagame Enclave bunker and the like.

## Changelog
:cl:
add: Added Enclavophobia. An admin-only brain trauma.
/:cl:

### CODE REVIEW

**Comment by ThyBaron** [comment]
Weeeeeeeeeeeeeeeeell, maybe? What's stopping folk from ignoring this outright and going on with their day?

**Comment by EgorDinamit** [comment]
> Weeeeeeeeeeeeeeeeell, maybe? What's stopping folk from ignoring this outright and going on with their day?

Phobia works the way, that if they see/hear anything from the list of items/words - they'll get a random phobia effect: Temporary blindness, stun, etc.
They can't ignore it mechanically, that's how every phobia works.

**Comment by ogrigbe** [comment]
no sorry, silly PR not happening.

**Comment by EgorDinamit** [comment]
Smh no admin-only meme traumas.

**Pull request closed without merging**
