### PR TITLE
Changes salvage loot drops

### PR DESCRIPTION
**Pull request by EgorDinamit**
## About The Pull Request

- Wrecks now check for TECHNOPHREAK trait for calculating how much salvage you can receive.
- High tier salvage is now much more rare.
- High tier salvage can contain more tools and interesting items, not just "haha, funny blueprint and welding tool".
- Low tier salvage may have glass, titanium, silver or gold in it.

## Why It's Good For The Game

High tier salvage was only good in rare cases and even then it was rather common and in the end you'd have 999 blueprints(that nobody wants) and welding tools.
There is now a reason to take low tier salvage, since it may contain useful materials and not just metal.
Craftsmanship trait is now actually useful.

## Changelog
:cl:
tweak: Craftsmanship trait is now actually useful when salvaging wrecks.
tweak: More possible loot in low and high tier salvages.
balance: High tier salvage is now much more rare.
/:cl:

### CODE REVIEW

**Comment by AdamElTablawy** [comment]
weirdly enough this makes high tier salvage worse because now it doesn't drop the good gun parts as often anymore

nobody wants switchblades and shit like that, they want superlight alloys

**Comment by EgorDinamit** [comment]
If that's the case, Adam, I could instead remove all the random stuff from the high-tier salvage and add a new type of it, which would only contain tools and stuff like that.

**Comment by AdamElTablawy** [comment]
do that

**Comment by EgorDinamit** [comment]
Integration test seems to have a random runtime, unrelated to the PR.
Could someone re-run checks?

**Pull request merged**
