### PR TITLE
Adds a Radio Station & Radio Host

### PR DESCRIPTION
**Pull request by Warfan1815**
## About The Pull Request

Adds a radio host role with a good amount of money, but no armour, that is meant to inform the wasteland about stuff (and maybe be payed off to put a slant) and access to the radio broadcast console aswell as spawning in the radio station. He does require some good amount of time on the server to play however.

tweaks the radio station wasteland building into a full blown radio station, with shutters to protect it from roundstart rush, locks to add, an autolathe to use, and a radio broadcast console to broadcast only from.

tweaks the comms console into a radio broadcast console, will still be usable as a comms console (if you somehow get captains access, something the radio host doesn't have) but is mainly transformed into a one-stick-only sort of console.

## Why It's Good For The Game

Is a way to finally vindicate all those people who want to be journalists but have the inability to properly get started, and is a good way to generate merc RP and faction influence/spy RP as they vy to put their own slant on the story. As well as finally making people who join the round not confused about what is going on as they receive news through broadcasts.

## Changelog
:cl: Warfan1815
add: A radio host with the wallet & the setup to broadcast good and loud, being the only person with access to an announcement system & having an entire radio station at his disposal we've finally got a journalist worthy of listening to.
tweak: tweaked the radio station into a more viable radio station with various new and improved features as well as an extension.
tweak: tweaked the comms console into a radio broadcast console, most comms console features still available although unless it's the announcement function they require admin-only-obtainable access.
/:cl:

### CODE REVIEW

**Comment by dawsonkeyes** [comment]
How does the console work? Does it use the announcement system? Is it customized to not be a giant in-your-face announcement, but rather another passing message that's highlighted differently?

**Comment by Warfan1815** [comment]
I've removed audio from the announcement as I realised it would be pretty annoying, still rather prominent but people who do not like it can always customise their preferences to ignore announcements.

**Comment by githubuser4141** [comment]
This seems like an interesting idea, maybe adding a co-DJ/radio mechanic/janitor/support person would be a good idea so you're not the only person in the tower, IMO the shopkeeper role tends to be a lot more interesting if you have a competent coworker.

**Comment by Warfan1815** [comment]
> This seems like an interesting idea, maybe adding a co-DJ/radio mechanic/janitor/support person would be a good idea so you're not the only person in the tower, IMO the shopkeeper role tends to be a lot more interesting if you have a competent coworker.

I would prefer the radio host hire then spawn with a co-worker, adds more RP opportunities

**Comment by Warfan1815** [comment]
I'm going to rebase this.

**Pull request closed without merging**
